baseURL = 'https://4n6.observer/'
languageCode = 'it-it'
title = 'Artifact Zero'

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"

[params]
  description = 'Digital & Mobile Forensics Insights by Observer Zero'
  author = 'Observer Zero'
