baseURL = 'https://4n6.observer/'
languageCode = 'it-it'
title = 'Artifact Zero'

[params]
  description = 'Digital & Mobile Forensics Insights by Observer Zero'
  author = 'Observer Zero'

[menu]
  [[menu.main]]
    name = 'Disclaimer'
    url = '/disclaimer/'
    weight = 10
